version: 2.1

orbs:
  slack: circleci/slack@4.12.0
  node: circleci/node@5.2

jobs:
  monitor-errors-in-prod:
    docker:
      - image: cimg/base:stable
    resource_class: small
    working_directory: ~/repo

    steps:
      - checkout  
      - node/install:
          install-yarn: true
          node-version: '18.20.2'
      - run: node --version
          
      - run: yarn

      - save_cache:
          paths:
            - ~/.npm
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: 'Run tests'
          command: npm run test:jest
      - slack/notify:
          channel: alerts
          event: fail
          template: basic_fail_1


workflows:
  test:
    jobs:
      - monitor-errors-in-prod:
          context:
            - notifiers
